name: CI
on: [push, pull_request]
jobs:
  macOS:
    runs-on: macos-10.15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'recursive'
    - name: Install Python
      run: brew install python
    - name: Install Boost
      run: ./installBoost.sh
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake ../ -DBOOST_ROOT=/opt/boost -DCMAKE_INSTALL_PREFIX=../stage
    - name: Build
      run: cd build && make -j 2 VERBOSE=1
    - name: Install
      run: cd build && make install VERBOSE=1
    - name: ls
      run: ls -R stage
    - name: otool libtest
      run: otool -l stage/lib/libtest.dylib
    - name: otool libpytest
      run: otool -l stage/lib/pytest/libpytest.so
    - name: nm libtest
      run: nm -C stage/lib/libtest.dylib
    - name: nm -D libtest
      run: nm -D -C stage/lib/libtest.dylib
    - name: nm libpytest
      run: nm -C stage/lib/pytest/libpytest.so
    - name: nm -D libpytest
      run: nm -D -C stage/lib/pytest/libpytest.so
    - name: Run tests
      run: ./test.sh
