name: CI
on: [push, pull_request]
jobs:
  macOS:
    runs-on: macos-10.15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'recursive'
    - name: Install Boost
      run: |
        wget https://dl.bintray.com/boostorg/release/1.74.0/source/boost_1_74_0.tar.gz
        tar -xf boost_1_74_0.tar.gz
        cd boost_1_74_0
        ./bootstrap.sh --with-python=python3 --prefix=/opt/boost
        sudo ./b2 -j 2 --with-python install
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake ../ -DBOOST_ROOT=/opt/boost -DCMAKE_INSTALL_PREFIX=../stage
    - name: Build
      run: cd build && make -j 2 VERBOSE=1
    - name: Install
      run: cd build && make install VERBOSE=1
    - name: ls
      run: ls -R stage
    - name: otool libtest
      run: otool -l stage/lib/libtest.dylib
    - name: otool libpytest
      run: otool -l stage/lib/pytest/libpytest.so
    - name: nm libtest
      run: nm -C stage/lib/libtest.dylib
    - name: nm libpytest
      run: nm -C stage/lib/pytest/libpytest.so
    - name: Run tests
      run: ./test.sh
